# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b26fd7b1dca9c810878189ddc893da827e59cdf0daf79fc57634d2b8c95e11992ab828c303b316a9ab1ac5592c1de3932d24ee7c72b88eff855164ee9f7fe61

test:
  secret_key_base: b6aeba2435bac02273617252354a081898097a65038191fce9d84d0709469898161a4451a958d12a5a65ea53bf4db027260eea3e05bceeb1b622ba5a5f8c2f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
